# Generated by Django 4.0.4 on 2022-07-24 00:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('gst', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=200)),
                ('total_product_amount', models.CharField(max_length=200)),
                ('total_tax_amount', models.CharField(max_length=12)),
                ('total_discount_amount', models.CharField(max_length=12)),
                ('grand_total', models.CharField(max_length=12)),
                ('user_id', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=255)),
                ('item_sku', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('item_tax_rate', models.FloatField()),
                ('item_recieved_quantity', models.IntegerField()),
                ('item_damage_quantity', models.IntegerField()),
                ('item_return_quantity', models.IntegerField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_title', models.CharField(max_length=200)),
                ('item_sku', models.CharField(max_length=200, unique=True)),
                ('item_price', models.FloatField()),
                ('item_purchase_price', models.FloatField()),
                ('item_stock_quantity', models.IntegerField()),
                ('item_hsn_code', models.CharField(max_length=200)),
                ('item_tax_rate', models.IntegerField()),
                ('item_images', models.TextField()),
                ('item_desc', models.TextField()),
                ('item_category', models.TextField()),
                ('item_attributes', models.TextField()),
                ('user_id', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=200)),
                ('total_product_amount', models.CharField(max_length=200)),
                ('total_tax_amount', models.CharField(max_length=12)),
                ('total_discount_amount', models.CharField(max_length=12)),
                ('grand_total', models.CharField(max_length=12)),
                ('user_id', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=255)),
                ('item_sku', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('item_tax_rate', models.FloatField()),
                ('item_recieved_quantity', models.IntegerField()),
                ('item_damage_quantity', models.IntegerField()),
                ('item_return_quantity', models.IntegerField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=200)),
                ('total_product_amount', models.CharField(max_length=200)),
                ('total_tax_amount', models.CharField(max_length=12)),
                ('total_discount_amount', models.CharField(max_length=12)),
                ('grand_total', models.CharField(max_length=12)),
                ('user_id', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=255)),
                ('item_sku', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('item_tax_rate', models.FloatField()),
                ('item_recieved_quantity', models.IntegerField()),
                ('item_damage_quantity', models.IntegerField()),
                ('item_return_quantity', models.IntegerField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('gst', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('isActive', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
